### ISSUE TITLE
client.send doesn't wait for proto.proto to be loaded

### ISSUE THREAD

**Issue by FINDarkside** [riemann/riemann-nodejs-client#35]
Seems like this library is asynchronously loading `/proto/proto.proto`, but it doesn't actually wait for it to be loaded when trying to send message. There also doesn't seem to be any api which we can use to detect when it has loaded.

```
TypeError: Cannot read property 'lookupType' of undefined
    at _serialize (/mnt/c/Users/myPath/riemann-test-client/node_modules/riemann/riemann/serializer.js:26:35)
    at Object.exports.serializeMessage (/mnt/c/Users/myPath/riemann-test-client/node_modules/riemann/riemann/serializer.js:61:10)
    at tcpSocket.<anonymous> (/mnt/c/Users/myPath/riemann-test-client/node_modules/riemann/riemann/client.js:39:30)
    at Client.send (/mnt/c/Users/myPath/riemann-test-client/node_modules/riemann/riemann/client.js:171:18)
```

**Comment by perezd** [comment]
that's an interesting catch, would you be willing to submit a PR to address this?

**Comment by perezd** [comment]
FWIW, this used to be synchronous, before the 2.x switch to protobufjs. This was a miss when it was changed.

**Comment by perezd** [comment]
Looks like you could observe this as part of a proposed change:
https://github.com/perezd/riemann-nodejs-client/blob/master/riemann/serializer.js#L29

**Comment by smarigowda** [comment]
I am also observing this issue. How to solve this ? Thanks.

**Comment by jamtur01** [comment]
As @perezd suggested it needs the load being observed to ensure it handles the order correctly.

**Comment by perezd** [comment]
I would suggest submitting a PIR that changes this to use loadSync instead of load:
https://github.com/riemann/riemann-nodejs-client/blob/master/riemann/serializer.js#L17

This file is trivially small and would ensure the timing is resolved.

**Comment by jamtur01** [comment]
@perezd I've tried that but no luck. I'm not in the NodeJS world and I don't have a lot of time beyond what I did today.

**Comment by smarigowda** [comment]
Thank for the fix. Could you please publish new version to npm, thank you. Or will I be able to do that, I don't think so.

**Comment by perezd** [comment]
Should be available now: https://www.npmjs.com/package/riemann

**Comment by smarigowda** [comment]
Thank you.
