### ISSUE TITLE
2.0.0 loses metric value on serialization

### ISSUE THREAD

**Issue by FINDarkside** [riemann/riemann-nodejs-client#36]
I cannot get `2.0.0` to work, it loses the metric value every single time. I've added couple `console.log` calls [here](https://github.com/perezd/riemann-nodejs-client/blob/master/riemann/client.js#L39) and noticed that it's the serialization that is losing `metric` field.

contents:
```
{
    "events": [
        {
            "service": "buffet_plates",
            "tags": [
                "nonblocking"
            ],
            "host": "LAPTOP-91M3C9AJ",
            "time": 1588754603,
            "metric_f": 252.2
        }
    ]
}
```

After calling `Serializer.deserializeMessage(Serializer.serializeMessage(contents))` it becomes:

```
{
    "events": [
        {
            "time": "1588754603",
            "service": "buffet_plates",
            "host": "LAPTOP-91M3C9AJ",
            "tags": [
                "nonblocking"
            ]
        }
    ]
}
```

Everything works fine with `1.1.1`

**Comment by perezd** [comment]
my guess is this was caused by the switch to use protobufjs instead of the original protobuf library we were using in the 1.x branch. Perhaps the schema isn't working as expected with protobufjs?

**Comment by perezd** [comment]
One theory, noticed that the proto file was not declaring syntax explicitly, can you patch this locally: https://github.com/perezd/riemann-nodejs-client/commit/c7e4c10a4b8014e36245a71e6fb059423d9a8202

and see if it shows up? Otherwise, we need to figure out why protobufjs is dropping that field.

**Comment by FINDarkside** [comment]
Hi, thanks for the answer. Declaring syntax explicitly does not seem to fix the issue. I've decided to use telegraf and use its riemann output instead, so I won't spend more time on this.

One thing I forgot to mention in the title, weirdly it works if you rename `metric_f` to `metric` in the proto file and payload.

**Comment by jayeshjk** [comment]
Hi @perezd ,

We found in our investigation that `metric_f` is getting lost in serialization as protobufjs expects it as `metricF`, see the example here: https://www.npmjs.com/package/protobufjs#using-proto-files. We had to add change like this: https://github.com/cloudfoundry-incubator/service-fabrik-broker/blob/359cbb816a6243f70f113fdecd3471051756f9e8/broker/data-access-layer/event-logger/src/EventLogRiemannClient.js#L162

Adding it as it might be useful in fixing this.
